export const Authors = [
  {
    firstName: "Dicky",
    lastName: "Kitchen Jr",
    website: "https://dickykitchenjr.com/",
    socialMedia: { instagram: "https://www.instagram.com/dicky_kitchen_jr/" },
    umbrellaGenre: ["thriller", "childrens"],
    subGenre: [
      "Psychological Thriller",
      "Domestic Thriller",
      "Children's Tongue Twister",
    ],
    bio: [
      `Introducing Dicky Kitchen Jr., a versatile author whose captivating tales encompass heart-stopping thrillers starring "The Average Man" and enchanting children's stories, such as "The True Tale of Peter Piper," a whimsical reimagination of the classic tongue twister. With a background in healthcare as a Physical Therapist Assistant and a self-taught front-end developer, Dicky's diverse experiences infuse authenticity into his vividly imagined worlds. As a loving husband and father, he embraces the art of storytelling out of pure passion, evident in his debut novel that earned him a coveted spot as a top 10 finalist in the "2020 New Author" contest by Balancing Books and Bottles. Praised with a remarkable 4.8 out of 5 star rating on Amazon for his first novel, Dicky is not only a master storyteller but also a devoted supporter of the writing community, actively engaging with fellow authors on his discord server "BookInd".`,
    ],
  },
  {
    firstName: "Elisa",
    lastName: "Menz",
    website: "https://sites.google.com/view/elisamenz",
    socialMedia: { instagram: "https://www.instagram.com/mayaseranawriter/" },
    umbrellaGenre: ["fantasy", "romance"],
    subGenre: ["Urban Fantasy", "Romantic Comedy", "High Fantasy"],
    bio: [
      `Elisa Menz is a self-taught writer and a fantasy literature fan. Born in Bolivia, she grew up surrounded by mythical creatures and supernatural folklore, through local writers and storytellers. Inspired by those tales, she started writing her own stories at a young age.`,
      `Now living in Chile, she works full time as a writer, while dawdling in video game programming, comic design, and alternative sources of storytelling. A member of the Chilean Tolkien Society and an avid reader of fantasy classics, her work is heavily influenced by authors like David Eddings, Raymond E. Feist, and Robin Hobb.`,
      `Her stories are full of witty, sweet, and hilarious characters, always with a pinch of magic.`,
    ],
  },
  {
    firstName: "Brittany",
    lastName: "Putzer",
    website: "https://brittanyputzer.com",
    socialMedia: {
      instagram: "https://www.instagram.com/author.brittanyputzer/",
      facebook: "https://www.facebook.com/authorbrittanyputzer/",
      tiktok: "https://www.tiktok.com/@Brittany.putzer",
      twitter: "https://twitter.com/brittanyputzer",
    },
    umbrellaGenre: ["romance"],
    subGenre: ["Rom Com", "Paranormal Romance", "Adventure", "Women's Fiction"],
    bio: [
      `Hi! My name is Brittany and I'm addicted to romance books. I am married to my high school sweetheart, I have 2 wild boys, 3 crazy cats, a scaled murderer, fur potato, and I live in sunny Florida.`,
      `I read to escape life for awhile. Although I enjoy page surfing, my passion is writing unique tales with shocking twists and multiple love interests. In 2020 I published my first book and now I have 4 out with 125 paperbacks sold, 360 eBooks delivered, and over 13,000 pages turned on KU!`,
      `I’m a mood reader and writer. So the first 3 books I published are clean YA romances with sweet heat, but my newest release is a HIGH heat HEA with wolf shifters.`,
      `Within all my books you can expect: Steam, Unexpected plot twists, Relatable characters, Strong female characters, Encouragement through troubling times`,
    ],
  },
  {
    firstName: "Stephen",
    lastName: "Mills",
    website: "https://mayhemmills.com",
    socialMedia: {
      instagram: "https://www.instagram.com/Stephen.mills.writes/",
      facebook: "https://www.facebook.com/pursuitofmayhem",
    },
    umbrellaGenre: ["horror", "fantasy"],
    subGenre: ["Dark Urban Fantasy", "Dark Historical Fantasy"],
    bio: [
      `A soggy native of Washington State, Stephen Mills escaped as soon as he came to his senses by joining the US Navy. Many adventures ensued, some of which Stephen remembers fondly, and after tricking an amazing woman into marrying him he left the Naval Service. An undiagnosed yet temporary bout of mild insanity ensued in which Stephen convinced his wife to move back home to Washington. Realizing their mistake, they then found themselves in the small burg of Monument, Colorado...unfortunately Colorado is cold and snowy, so after braving the Rocky Mountains for almost a decade, they decided to enjoy the hellish heat of Phoenix before finally settling near Nashville, Tennessee.`,
      `Stephen's most enjoyable hobbies are also those that are decidedly antisocial, such as hiking and fishing. It is difficult to put a finger on why he decided to begin writing books but it probably has something to do with sharing his nightmares with others.`,
      `Thankfully, being an author isn't a team sport, so now you can enjoy his unique brand of dark humor and gory adventure in every book.`,
    ],
  },
  {
    firstName: "Miriam A",
    lastName: "Maddock",
    website: "https://mamaddockauthor.ie",
    socialMedia: {
      instagram: "https://www.instagram.com/ma.maddock_author",
      facebook: "https://www.facebook.com/thesixthamuletseries",
      goodreads: "https://www.goodreads.com/author/show/21176498.M_A_Maddock",
      twitter: "https://twitter.com/mamaddock1_a?t=kW8VZpxP001bt4JBk8S0DQ&s=09",
    },
    umbrellaGenre: ["fantasy"],
    subGenre: ["Historical Fantasy Fiction"],
    bio: [
      `My name is Miriam and I was born and raised in Dublin, Ireland.`,
      `Having dabbled in other ‘interests’ over the years (I won’t bore you), in the background, however, I was always an avid reader, with words constantly floating around in my mind yet doing nothing about them—in a literary sense. I used to always say, ‘One day, I’ll write that book!’ But never seemed to get around to doing it. I think the mere thought of putting those words—along with my imagination—to literary use, was daunting, therefore, I was always putting it off. That is, until 2011 when I finally took the plunge and picked up that pen and notebook (still have them, too!). I began to string those words into sentences, then paragraphs, then pages, eventually joining them together to create my first novel—The Sixth Amulet - Book One (released October 2022). Then my imagination had other plans; it didn’t want to stop at just one. Why would it? And so, novel one turned into another, The Moon Chasers - Book Two of The Sixth Amulet - released June 2023) . Who knows where it will end?`,
      `I believe everyone has a story to tell, a potential book tucked away inside them, dying to get out. And all that’s needed to create it is a simple recipe: a pen and a notebook. So, open your mind and let your imagination roam through the endless possibilities it has to offer … then simply write! `,
      `I hope you enjoy reading The Sixth Amulet and The Moon Chasers and promise to have part three of my epic adventure – A Flutter on the Wind - out by Spring 2024. Happy reading!`,
    ],
  },
  {
    firstName: "Becky",
    lastName: "Wright",
    website: "https://beckywrightauthor.com/",
    socialMedia: {
      instagram: "https://www.instagram.com/beckywrightauthor/",
      facebook: "https://www.facebook.com/BeckyWrightAuthor",
      twitter: "https://twitter.com/BeckyWrightAuth",
      tiktok: "https://www.tiktok.com/@beckywright_author",
    },
    umbrellaGenre: ["thriller", "fantasy", "horror"],
    subGenre: [
      "Gothic Horror",
      "Gothic Thriller",
      "Historical Horror",
      "Historical Romance",
    ],
    bio: [
      `Becky Wright is a Best-Selling British author with a passion for Gothic literature, history, the supernatural and things that go bump in the night. She lives with her family in the heart of the Suffolk countryside, surrounded by rolling fields, picturesque timber-framed villages, rural churches… and haunted houses. With her inherent fascination for the macabre, her writing leans towards the dark side.`,
    ],
  },
  {
    firstName: "Barbara",
    lastName: "Lennox",
    website: "https://barbaralennox.wordpress.com/",
    socialMedia: {
      instagram: "https://www.instagram.com/barbaralennoxauthor/",
    },
    umbrellaGenre: ["fantasy", "romance", "thriller"],
    subGenre: [
      "Historical Fantasy Fiction",
      "Historical Thrillers",
      "Historical Romance",
    ],
    bio: [
      `Barbara Lennox is a Scottish historical fiction writer who writes stories set in first millennium Scotland. Drawing on her extensive research and vivid imagination, she brings to life the struggles, triumphs and tragedies of the people who lived in this fascinating period of Scottish History. Her critically acclaimed trilogy, The Trystan Trilogy, is a reimagining of the doomed story of Tristan and Isolde, set in the gritty realities of 5th century Scotland. She also writes and publishes prize-winning short stories and poetry. When she's not writing, she can be found at the top of a mountain, or in in her garden.`,
    ],
  },
  {
    firstName: "Steven J",
    lastName: "Morris",
    website: "https://sjmorriswrites.com/",
    socialMedia: {
      instagram: "https://www.instagram.com/steven.j.morris.writer/",
      facebook: "https://facebook.com/steven.j.morris.writer",
    },
    umbrellaGenre: ["fantasy"],
    subGenre: ["Urban Fantasy"],
    bio: [
      `Engineer, husband, and father of three wonderful girls by day. Fantasy fiction writer by night (and other random times he's not taxiing kids, pulling hair out of drains, helping with math and science homework, coaching soccer, remodeling rooms, and walking the dogs).`,
    ],
  },
  {
    firstName: "Cheryl",
    lastName: "Burman",
    website: "https://cherylburman.com/",
    socialMedia: {
      instagram: "https://www.instagram.com/cherylburmanauthor/",
      facebook: "https://www.facebook.com/CherylBurmanAuthor/",
      twitter: "https://twitter.com/cr_burman",
    },
    umbrellaGenre: ["fantasy", "drama", "childrens"],
    subGenre: [
      "Historical Fiction",
      "Historical Fantasy",
      "Children's Fantasy",
    ],
    bio: [
      `Originally from Australia, Cheryl Burman now lives in the Forest of Dean, UK, a place which has inspired the likes of Tolkien and Rowling. She’s the author of two award winning novels and a novella for grownups, and a trilogy and its prequel for youngsters (although Mum, Dad and the grans love them too). Her flash fiction and short stories have won various awards and some of these are included in her collection, Dragon Gift while several are published in various anthologies.`,
      `As Cheryl Mayo, she is the chair of Dean Writers Circle and a founder of Dean Scribblers, which encourages creative writing among young people in her community.`,
    ],
  },
  {
    firstName: "Louise",
    lastName: "Murchie",
    website: "https://louisemurchie.com/",
    socialMedia: {},
    umbrellaGenre: ["romance"],
    subGenre: ["Second Chance", "Scottish", "Cinnamon Roll Alpha"],
    bio: [
      `Louise lives in the West Midlands with her husband and three children. Scottish born and bred alas, she doesn't live there any more. Her heart though always will be in the mist-covered mountains.`,
      `She writes for the more mature characters, often in a sweet-with-heat setting and getting their second chance. Not all of them are Scottish; though there's going to be a connection to that place, somehow!`,
    ],
  },
  {
    firstName: "Louise",
    lastName: "Hope",
    website: "https://www.notoriouswriter.com/",
    socialMedia: { instagram: "http://www.instagram.com/the_notoriouswriter" },
    umbrellaGenre: ["romance"],
    subGenre: ["Dark Romance", "Mafia Romance", "Suspense"],
    bio: [
      `Louise Hope, also known as L. Hope or The Notorious Writer, started her writing career back in 2020.`,
      `Specialising in Mafia Romance, Dark Romance, and Romantic Suspense, and best known for The Notorious Five series.`,
      `Based in the UK, and in the rainiest part of the country, she enjoys a good cup of tea and a great book. Like a true brit.`,
      `You can find her work on Patreon, Ream and Inkitt, with all published work available on Amazon.`,
      `If you like morally grey men and bad a$$ females, her books are the ultimate indulgence.`,
    ],
  },
  {
    firstName: "N.",
    lastName: "Dune",
    website: "https://nduneauthor.com/",
    socialMedia: {
      instagram: "https://www.instagram.com/nduneauthor",
      facebook: "https://www.facebook.com/groups/2682434541968398",
      twitter: "https://twitter.com/AuthorNDune",
      tiktok: "https://www.tiktok.com/@nduneauthor",
    },
    umbrellaGenre: ["romance", "fantasy"],
    subGenre: ["Paranormal Fantasy Romance", "Romantic Suspense"],
    bio: [
      `Hi, I am a British author writing all sorts of deliciously steamy romance across the genres. If you enjoy a slow burn that leads to some seriously steamy action, a little darkness (check the triggers, as some are quite dark) and some angst thrown in, then my books are for you.`,
    ],
  },
  {
    firstName: "H. S.",
    lastName: "Matthews",
    website: "https://hsmatthews.com/",
    socialMedia: {
      instagram: "https://www.instagram.com/thehsmatthews/",
      twitter: "http://twitter.com/thehsmatthews",
    },
    umbrellaGenre: ["fantasy"],
    subGenre: ["Young Adult"],
    bio: [
      `A fantasy fiction author from the UK. I live with my husband and two dogs (mad cocker spaniels).`,
      `I have four books published in my Lottie Jones and the Magical Realms series with the final book publishing in September.`,
      `Currently writing a dark fantasy novel definitely aimed at the adult market.`,
    ],
  },
  {
    firstName: "Hazel",
    lastName: "Jacks",
    website: "https://www.hazeljacks.com/",
    socialMedia: {
      instagram:
        "https://www.instagram.com/authorhazeljacks/?igshid=YmMyMTA2M2Y=",
      tiktok: "https://www.tiktok.com/@hazeljacksauthor",
      facebook:
        "https://m.facebook.com/authorhazeljacks?wtsid=rdr_0abkJyA3wK2IsUUbE&_rdr",
    },
    umbrellaGenre: ["romance"],
    subGenre: ["Contemporary", "New Adult and College"],
    bio: [
      `Hazel is fueled by boba tea, pop-punk/emo music, the beach, and sour candy. She lives on the West Coast with her husband and daughter.`,
    ],
  },
  {
    firstName: "Cassandra",
    lastName: "Celia",
    website: "https://cassandracelia.carrd.co/",
    socialMedia: {
      instagram: "https://instagram.com/authorcassandracelia",
      tiktok: "https://tiktok.com/@authorcassandracelia",
      facebook: "https://www.facebook.com/authorcassandracelia",
    },
    umbrellaGenre: ["fantasy", "thriller", "horror"],
    subGenre: ["Horror/Thriller/Paranormal"],
    bio: [
      `Cassandra is a Maryland bookseller, turned author. She writes horror, paranormal, and dark fiction, and she obsesses over stories with love, death, ambiguous endings, and everything in between. In her books, she takes inspiration from all things dark and spooky, and she absolutely loves writing about angry, scorned women.`,
      `Stars and Other Monsters is her debut novel. `,
      `Stay up to date by visiting her website, www.cassandracelia.carrd.co.`,
    ],
  },
  {
    firstName: "V.B.",
    lastName: "Emanuele",
    website: "https://www.vbemanuele.com/",
    socialMedia: {
      instagram: "https://instagram.com/vbemanuele",
      tiktok: "https://www.tiktok.com/@vbemanuele.author",
      facebook: "https://www.facebook.com/vbemanuele",
    },
    umbrellaGenre: ["romance"],
    subGenre: ["Dark Romance", "Billionaire Romance", "Mafia Romance"],
    bio: [
      `V.B. Emanuele (Valentina Emanuele) is an award-winning author who began writing professionally for a serial, visual story app, under the username VioletBlue. She quickly found herself wanting to expand her art, and wrote her first online novel, The Veil, in 2019. After the rapid success of the book, she released several more online novels before deciding she wanted to publish them. Just Business was the first book to launch the Club Euphoria Novels and Valentina's publishing debut.`,
      `She has lived in both Europe and the United States and obtained a Fine Arts degree and English Literature degree. When she is not writing or reading, she can be found active outdoors, participating in fitness challenges and events, cooking, or traveling.`,
    ],
  },
  {
    firstName: "Caitriona",
    lastName: "Drexler",
    website: "https://caitrionadrexler.wixsite.com/caitriona-drexler",
    socialMedia: {
      instagram: "http://www.instagram.com/author_tri_drexler",
      tiktok: "http://www.tiktok.com/@author_tri_drexler",
      facebook: "http://www.facebook.com/tridrexler",
    },
    umbrellaGenre: ["romance"],
    subGenre: ["fantasy", "sci-fi", "contemporary"],
    bio: [
      `Caitriona “Tri” Drexler is a data-driven art historian by day and a genre-hopping indie author by night. As an avid reader of romance, Tri takes inspiration from her favorite genre when writing. She wanted to write something different from the same tired romance plots she kept getting sucked into. So she started writing her own.`,
      `Tri was born and raised in New Jersey, where she still lives with her husband, son, and two cats. After graduating college with a BA in Art History, Tri got a job in data acquisition for an art database. Though this was not Tri’s dream museum job, she grew to love working with data, becoming obsessed with spreadsheets, pivot tables and KPIs.`,
      `And now, her new obsession is writing epic love stories full of spice.`,
    ],
  },
  {
    firstName: "Linzvonc",
    lastName: "",
    website: "https://www.linzvonc.co.uk/",
    socialMedia: {
      instagram: "http://www.instagram.com/linzvonc",
    },
    umbrellaGenre: ["romance"],
    subGenre: [
      "Steamy Romance",
      "Mafia Romance",
      "Age Gap Romance",
      "Taboo Romance",
    ],
    bio: [
      `I’m a steamy romance author with one thing on my mind…your escapism! I love coffee and chocolate and I’m obsessed with my dog. When I’m not writing I’m reading!`,
    ],
  },
  {
    firstName: "GiGi",
    lastName: "Meier",
    website: "https://www.gigimeier.com/",
    socialMedia: {
      instagram: "https://www.instagram.com/gigimeiermedia/",
      facebook: "https://www.facebook.com/gigimeiermedia/",
    },
    umbrellaGenre: ["romance"],
    subGenre: ["Dark Romance", "Sports Romance"],
    bio: [
      `GIGI MEIER retired from a thirty-year career in corporate America to write romance novels about strong female characters and their complicated, swoon-worthy men. She loves telling stories and figuring out why her characters do what they do. With heartbreaking angst, panty-dropping lust, and enviable love, her stories linger long after you close the book.`,
      `When GiGi is not eating over her laptop, she likes to spend time in the pool with her children, walk her furry babies, and film videos for Instagram and YouTube. Whether working out with her trainer, attending a book club, or hosting a game night, she loves connecting with new people and making friends.`,
    ],
  },
  {
    firstName: "Bethany",
    lastName: "Bauerle",
    website: "https://www.authorbethanybauerle.com/",
    socialMedia: {
      instagram: "https://www.instagram.com/authorbethanybauerle",
      facebook: "https://www.facebook.com/authorbethanybauerle",
      tiktok: "https://www.tiktok.com/author_bethany_bauerle",
    },
    umbrellaGenre: ["childrens"],
    subGenre: ["Family", "Disabilities", "Autism"],
    bio: [
      `Was born and raised in the great state of Indiana, where she still lives with her husband and two children.`,
      `Her love for reading and writing began at a very young age, when her mother brought her to their local library. Where Bethany fell in love with the imaginary worlds created by authors such as C. S. Lewis, Roald Dahl, and Shel Silverstein. She ended up writing a short story and discovered that she had passion for writing as well.`,
      `Her second-grade teacher saw her love of reading and writing and encouraged Bethany to continue, and just like that, an author was born!`,
      `Over the years her experience as a mommy to an amazing little boy who is autistic, and his incredible little sister inspired children's book (s). "They have shown me what real unconditional love and acceptance are about, and I wanted to share that love with others. While also teaching kids about kindness, compassion, and understanding of the the differences in all of us."`,
    ],
  },
  {
    firstName: "Ariana",
    lastName: "St. Claire",
    website: "https://www.arianastclaireauthor.com/",
    socialMedia: {
      instagram:
        "https://www.instagram.com/authorarianastclaire/?igshid=MzNlNGNkZWQ4Mg%3D%3D",
      facebook: "http://www.facebook.com/authorarianastclaire",
    },
    umbrellaGenre: ["romance"],
    subGenre: ["Sports Romance", "BDSM Themed Romance"],
    bio: [
      `Ariana can be found getting her Zen on while practicing hot yoga, going for a run, reading her favorite authors in the middle of the night, or having a bourbon on a Saturday while plotting the lives of her characters as they whisper and sometimes yell in her ear. She lives her own Happily Ever After with her amazing husband, who shares her love of racing, comic books, and Firefly, along with her two spirited also amazing boys who love reading books under a blanket just as much as she does!`,
    ],
  },
  {
    firstName: "Breanna",
    lastName: "Hicks",
    website: "",
    socialMedia: {
      instagram: "https://www.instagram.com/mrsbreannahicks/",
      facebook:
        "https://www.facebook.com/BreannaMcGinnisAuthor?mibextid=LQQJ4d",
      tiktok: "https://www.tiktok.com/@breanna.hicks11?_t=8dBv3gq3qDD&_r=1",
    },
    umbrellaGenre: ["romance", "thriller"],
    subGenre: ["Crime Thriller", "Psychological Thriller", "Romantic Thriller"],
    bio: [
      `Breanna Hicks, author of the new crime thriller trilogy, The Colorado Killer.`,
      `Breanna grew up in a rural town outside Kansas City, MO and still resides in the area with her husband and two dogs. When she’s not writing her latest crime thriller novel, Breanna enjoys being outside; whether it be reading, birdwatching with her husband, hosting BBQ’s, or simply enjoying the weather.`,
    ],
  },
  {
    firstName: "Deborah J.",
    lastName: "Lightfoot",
    website: "https://www.waterspell.net/",
    socialMedia: {
      instagram: "https://www.instagram.com/booksofwaterspell/",
      facebook: "https://www.facebook.com/WaterspellTrilogy",
    },
    umbrellaGenre: ["fantasy"],
    subGenre: ["Epic Fantasy", "Sword and Sorcery"],
    bio: [
      `Castles in the cornfield provided the setting for Deborah J. Lightfoot's earliest flights of fancy. On her father's farm in Texas, she grew up reading tales of adventure and reenacting them behind ramparts of sun-drenched grain. She left the farm to earn a degree in journalism and write award-winning books of history and biography. High on her bucket list was the desire to try her hand at the genre she most admired. The result is Waterspell, a complex, intricately detailed fantasy series about a girl and the wizard who suspects her of being so dangerous to his world, he believes he'll have to kill her … which troubles him, since he's fallen in love with her. There's magic, mystery, murder, and romance. Waterspell: An original save-the-world fantasy adventure with complicated characters, cosmic calamities, and the gothic sensibilities of "Jane Eyre."`,
    ],
  },
  {
    firstName: "AJ",
    lastName: "Ashton",
    website: "https://ajwriter72.wixsite.com/a-j-ashton",
    socialMedia: {
      instagram: "https://instagram.com/aashtonwriter?igshid=MzNlNGNkZWQ4Mg==",
    },
    umbrellaGenre: ["fantasy", "romance"],
    subGenre: ["Epic Fantasy"],
    bio: [
      `AJ Ashton was born in 1972, in Derbyshire, UK. She still lives in the area, juggling a full-time job and being a mother.`,
      `From the age of seven, after seeing a rather famous sci-fi film, for the first time. Her creativeness to write was born. Inspired by a strong princess being rescued by a notorious smuggler. She wrote sci-fi, but her passion was soon drawn to fantasy. Where the world of Zentos was born.`,
      `Outcast New Beginnings is the second book in the Tarrenfall Chronicles and the Zentos series. It will give you more insight into her fantasy world, with more mystical creatures, magic, and swords. There will also be even more romance.`,
    ],
  },
  {
    firstName: "Kelly",
    lastName: "Lord",
    website: "https://www.kellylord.co.uk/",
    socialMedia: {
      instagram: "https://www.instagram.com/k_l_lord",
      facebook: "https://www.facebook.com/author.klord",
    },
    umbrellaGenre: ["romance", "fantasy", "dystopian"],
    subGenre: ["Werewolf", "Monster", "Poly", "MM"],
    bio: [
      `Kelly Lord is best known for her steamy romance stories, from smoking-hot shifters, monsters, and hellhounds, to sizzling contemporary eroticism that will melt your kindle.`,
    ],
  },
  {
    firstName: "Meghann",
    lastName: "Crane",
    website: "https://meghanncraneauthor.wixsite.com/mysite",
    socialMedia: {
      instagram: "https://instagram.com/mcrane.author?igshid=OGQ5ZDc2ODk2ZA==",
    },
    umbrellaGenre: ["romance", "fantasy"],
    subGenre: ["Erotica"],
    bio: [
      `Meghann is a semi-new romance author who began her journey in 2020. Her stories are often filled with steamy, intense plots that end up in the happily ever after category.`,
      `Some of her works include: Falling for the Mafia Brothers on Galatea Loving My Brother’s Best Friend on Galatea Promised to the One I hate on KISSThe Secret Series which can be found on all major ebook retailers.`,
    ],
  },
  {
    firstName: "Martin",
    lastName: "Dukes",
    website: "https://www.mdukes-wildestdreams.com/",
    socialMedia: {
      instagram: "https://www.instagram.com/martin.dukes.wildest.dreams",
      tiktok: "https://www.tiktok.com/martindukeswildestdreams",
      facebook: "https://www.facebook.com/martindukesbooks",
      twitter: "https://twitter.com/martindukes5",
    },
    umbrellaGenre: ["fantasy"],
    subGenre: ["Epic Fantasy"],
    bio: [
      `I’ve always been a writer. It’s not a choice. It’s a compulsion, and I’ve been writing as long as I can remember. Lots of childish scribbles in notebooks, lots of rejection slips from publishers and agents testify to a craft long in the making. In addition, it has proved necessary to earn a living by other means whilst those vital skills mature. For thirty-eight years I taught Art and Graphic Design, thirty-seven of them in a wonderful independent girls’ school in Birmingham, UK. For much of the latter part of this career I was Head of Department, which gave me the opportunity to place my own stamp on Art education there, sharing with the pupils there my own love of Art and the History of Art. Over a decade I was able to lead annual visits to Florence, Venice and Rome (some of my favourite places on the planet) as destinations on my Renaissance Tour. These visits created memories that I shall cherish for the rest of my life.`,
      `I love history in general, reading history as much as I read fiction. I have a particular interest in the ancient world but I am also fascinated with medieval times and with European history in general. This interest informs my own writing to the extent that human relationships and motivations are a constant throughout the millennia, and there is scarcely a story that could be conceived of that has not already played itself out in some historical context. There is much to learn from observing and understanding such things, much that can be usefully applied to my own work.`,
      `Teaching tends to be a rather time-consuming activity. Since retiring, I have been able to devote much more of my time to writing and has meant that I am finally able to bring my work to the reading public’s attention. I like to think that my ideas are original and that they do not readily fall into existing tropes and categories.
I am not a particularly physical being. I was always terrible at sport and have rather poor physical coordination (as though my body were organised by a committee rather than a single guiding intelligence!). I tend to treat my body as a conveyance for my head, which is where I really dwell. My writing typically derives from dreams. There is a sweet spot between sleeping and waking which is where my ideas originate. I always develop my stories there. When I am writing it feels as though the content of my dreams becomes real through the agency of my fingers on the keyboard. I love the English language, the rich majesty of its vocabulary and its rhythmic possibilities. My arrival at this stage could hardly be describes as precocious. However, at the age of sixty-three, I feel that I have arrived at a place where I can create work of value that others may appreciate and enjoy.`,
    ],
  },
  {
    firstName: "Julia",
    lastName: "Slack",
    website: "https://www.juliaslackauthor.com/",
    socialMedia: {
      instagram: "http://www.instagram.com/juliaslackauthor",
    },
    umbrellaGenre: ["drama"],
    subGenre: ["Women's Historical Fiction"],
    bio: [
      `Julia Slack is a Brit in Barcelona. Her standalone historical fiction, set in 1960s Barcelona, is based on real places and events. It's available FREE on Kindle Unlimited!!`,
    ],
  },
  {
    firstName: "Khushi T.",
    lastName: "Saha",
    website: "",
    socialMedia: {
      instagram: "https://www.instagram.com/ktsromance/",
      facebook: "https://www.facebook.com/KhushiT.S",
      tiktok: "http://tiktok.com/@ktsromance",
    },
    umbrellaGenre: ["romance"],
    subGenre: ["Contemporary", "Interracial with South Asian/American Nuances"],
    bio: [
      `Bringing interracial romances with tons of heat, passion, and a healthy infusion of love. HEA is an ALWAYS!`,
      `ABOUT THE AUTHOR`,
      `Khushi T. Saha is a notorious daydreamer. And ask anyone close to her and they’ll tell you she’s a positive, mushy person, too. Enter in ‘writing romance novels’: what began as self-care to overcome personal trauma, ended up evolving into something much more fulfilling. Bringing stories of angst, personal growth, and passion (the steamier the better!) with some snarky humor to romantics all around has become a hunger she can’t seem to satiate. In fact, once she’s done with a story, there’s already another one a-brewin'.`,
      `And because she’s a first-generation Bangladeshi—born and raised in the US—the connection to the motherland is fierce. You’ll find South Asian nuances/representation purposely sprinkled throughout her novels.`,
      `When she's not writing, she's managing her craft business, obsessed with gardening in the spring and summer months, running around with her boys, and binge-watching murder shows/podcasts.`,
    ],
  },
  {
    firstName: "L.N.",
    lastName: "White",
    website: "https://lnwhitewrite.weebly.com/",
    socialMedia: {
      instagram: "https://instagram.com/author_l_n_white",
      facebook: "https://facebook.com/l.n.whitewrite",
      tiktok: "https://tiktok.com/@author_l_n_white",
    },
    umbrellaGenre: ["romance", "fantasy"],
    subGenre: ["New Adult", "Supernatural", "Dark Fiction"],
    bio: [
      `Author of The Haunted Series Trilogy, L. N. White has been creating stories since she hold a writing utensil. In high school, she started working on poems but moved back to books. The combined stories helped Lyn come up with The Haunted Series. She lives in Oklahoma City with her boyfriend and two furbabies. Now working part-time as an author and freelance writer to continue her dream of being a published author.`,
    ],
  },
  {
    firstName: "Garrett K.",
    lastName: "Jones",
    website: "http://www.archivesofthefivekingdoms.com/",
    socialMedia: {
      instagram: "https://instagram.com/gkj_publishing",
      facebook:
        "https://www.facebook.com/profile.php?id=100032106176877&mibextid=LQQJ4d",
      twitter: "https://twitter.com/gkj_publishing",
    },
    umbrellaGenre: ["fantasy"],
    subGenre: ["Epic Fantasy"],
    bio: [
      `Garrett is a fantasy novelist from Central California where he lives with his family. He holds a BA in Creative Writing from CSU Monterey Bay and an MAR in Biblical Studies from Liberty University Theological Seminary. When he is not writing or publishing he hosts The Write Way on his YouTube channel.`,
    ],
  },
  {
    firstName: "S.E.",
    lastName: "Green",
    website: "https://segreenauthor.com/",
    socialMedia: {
      instagram: "https://www.instagram.com/segreen.author/",
      facebook: "https://www.facebook.com/segreen.author",
      tiktok: "https://www.tiktok.com/@authorsegreen?lang=en",
    },
    umbrellaGenre: ["romance"],
    subGenre: ["Contemporary", "Why Choose", "Erotica"],
    bio: [
      `I'm a contemporary romance author that enjoys writing M/F romances as well as Why Choose with a variety of different tropes. My books tend to focus on heavy topics, but I wouldn't quite label them as Dark Romance.`,
      `~building romance around dreams~`,
    ],
  },
  {
    firstName: "Nikki",
    lastName: "Long",
    website: "https://nikkilongwrites.com/",
    socialMedia: {
      facebook: "https://www.facebook.com/nikkilongwrites",
    },
    umbrellaGenre: ["romance"],
    subGenre: ["Contemporary", "Paranormal"],
    bio: [
      `Hello! I love romance and if you’ve found me, then you must love romance too. I started writing romance novels in 2019 because I knew that I had some great stories to tell. Stories about strong, contemporary women who aren’t necessarily looking for romance, but it finds them. Stories that take the reader to different parts of the world. My novels are filled with humor, friendship, romance, and some sexy time too! But one thing you can count on–there is always a happy ending for the heroine!`,
      `I have worn a lot of hats in my life–actor, singer, college administrator, and now romance author. I am very lucky to share a home with a wonderful husband and a menagerie of dogs and cats. When time and money afford it, I also love to travel, which will often show up in my novels. Because there is nothing like romance and travel to make you happy!`,
    ],
  },
  {
    firstName: "Maxine",
    lastName: "Keith",
    website: "https://authormaxinekeith.com/",
    socialMedia: {
      instagram: "https://www.instagram.com/maxine_keith_",
      facebook: "https://www.facebook.com/maxinekeith",
    },
    umbrellaGenre: ["romance"],
    subGenre: [
      "YA",
      "Contemporary",
      "Supernatural",
      "Athletic",
      "Erotica",
      "Adult",
    ],
    bio: [
      `Maxine Keith is an indie author with 50 books across the romance genre. There is something for everyone. All her books are available on Kindle, KU, and Amazon.`,
    ],
  },
  {
    firstName: "Annie",
    lastName: "Charme",
    website: "https://anniecharme.com/",
    socialMedia: {
      instagram: "https://www.instagram.com/anniecharmeauthor/",
      facebook: "https://www.facebook.com/Anniecharmeauthor",
      twitter: "https://twitter.com/annie_charme",
    },
    umbrellaGenre: ["romance"],
    subGenre: ["Contemporary", "Romcom", "Suspense"],
    bio: [
      `I’m a graphic artist by day and author by night, writing real, raw, racy romance. My book boyfriends are inked heroes who like fat, fun, and feisty women (sounds familiar).`,
      `My goal is to spread body positivity through my fat and fabulous curvy heroines with a good serving of British humour on the side (not forgetting an extra helping of alpha goodness).`,
      `On the very rare occasion I’m not working in my day job...or night job as a writer, I'll be living my best life in the heart of England with my other half, two wildlings (otherwise known as Veruca Salt and Mike Teavee), and a randy cavalier pup.`,
      `My serious book fetish travels with me in our tin cruiser as we roam the English countryside. You’ll usually find me in a field somewhere or curled up on the sofa with a coffee (wine), blanket and dog to keep me cozy, and a good steamy book to make me w—warm.`,
      `Visit... www.anniecharme.com for all the linky-links, sign up to my newsletter and follow on social media.`,
      `Get in touch! I love hearing from readers.`,
    ],
  },
  {
    firstName: "C.S.",
    lastName: "Knight",
    website: "https://csauthor.wixsite.com/stories",
    socialMedia: {
      instagram: "https://www.instagram.com/c.s.stories/",
    },
    umbrellaGenre: ["fantasy"],
    subGenre: ["Fantasy Romance", "Paranormal Romance"],
    bio: [
      `C.S. is a Canadian author who lives in the boonies and enjoys writing and reading fantastical stories. She's a lover of twists, turns, laughs, bumpy rides, and the unexpected along the journey to a happy ending.`,
      `Her stories are generally geared toward and about adults (and most aren't filtered). She likes to experiment with various fantasy and paranormal romance tropes and sprinkle in a little humour and spice while she's at it.`,
      `Visit her website to learn more`,
    ],
  },
  {
    firstName: "Shanna P.",
    lastName: "Lowe",
    website: "https://www.shannaplowe.com/",
    socialMedia: {
      instagram: "http://www.instagram.com/author_shanna.p.lowe",
      tiktok: "http://www.tiktok.com/@author_shanna.p.lowe",
    },
    umbrellaGenre: ["fantasy", "childrens"],
    subGenre: ["MG Fantasy", "YA Fantasy"],
    bio: [
      `When Shanna P. Lowe was a little girl, she used to collect her mother's seed magazines and copy them word from word into a composition journal. This was an early and naive attempt at her childhood dream--an author. `,
      `By the time Shanna reached middle school, she began writing novel-length works. In high school, she published her first short story. Now Shanna is an award-winning writer with a BA in English Writing and several published short stories, articles, and poetry.`,
      `Shanna P. Lowe lives in the Pacific Northwest but grew up in Colorado. When she is not writing, Shanna is homeschooling her son and chasing around her clowder of cats.`,
    ],
  },
  {
    firstName: "Tobin",
    lastName: "Elliott",
    website: "",
    socialMedia: {
      instagram: "https://www.instagram.com/tobinelliott.horrorguy/",
      tiktok: "https://www.tiktok.com/@tobinelliott",
      facebook: "https://www.facebook.com/TheHorrorGuy91",
      twitter: "https://twitter.com/TheHorrorGuy91",
    },
    umbrellaGenre: ["horror"],
    subGenre: ["Vampire", "Werewolf", "Demon"],
    bio: [
      `Tobin Elliott writes ugly stories about bad people doing horrible things.`,
      `He used to be a Communications Specialist for a large corporation, and he also taught creative writing at two local universities for two decades.`,
      `He's had a few novellas published through various small presses, mostly out of print now. He's also had a few short stories placed in various anthologies, mostly still in print.`,
      `But his biggest claim to fame is the six-book horror series, The Aphotic. The books are`,
      `Bad Blood`,
      `Out For Blood`,
      `Blood Loss`,
      `Blood Pact`,
      `Blood Relations`,
      `Flesh and Blood`,
      `and all six books are available wherever you buy your books!`,
    ],
  },
  {
    firstName: "T.K.",
    lastName: "Toppin",
    website: "https://tktoppin.blogspot.com/",
    socialMedia: {
      instagram: "http://www.instagram.com/written.by.tktoppin/",
      tiktok: "https://www.tiktok.com/@tktoppin",
      facebook: "https://www.facebook.com/WrittenByTKToppin",
    },
    umbrellaGenre: ["scifi"],
    subGenre: ["Space Opera", "Speculative Fiction"],
    bio: [
      `T.K. Toppin writes character-driven tales, loaded with mystery, intrigue and adventure, navigating the realms of Science Fiction, Speculative Fiction and Space Opera.`,
      `T.K. was born, raised and lives in Barbados. When she's not writing, she can be found studiously working on her doctorate in Procrastination by binge-watching shows on streaming networks, doing absolutely nothing, and juggling the baffling realm of social media marketing.`,
    ],
  },
  {
    firstName: "Tony",
    lastName: "Riches",
    website: "https://www.tonyriches.com/",
    socialMedia: {
      twitter: "https://twitter.com/tonyriches",
      instagram: "https://www.instagram.com/tonyriches.author/",
      tiktok: "https://www.tiktok.com/@tonyriches.author",
      facebook: "https://www.facebook.com/tonyriches.author",
      goodreads: "https://www.goodreads.com/author/show/5604088.Tony_Riches",
    },
    umbrellaGenre: ["drama"],
    subGenre: ["Historical Fiction"],
    bio: [
      `Tony Riches is a full-time UK author of Tudor historical fiction. He lives with his wife in Pembrokeshire, West Wales and is a specialist in the lives of the Tudors. As well as his new Elizabethan series, Tony’s historical fiction novels include the best-selling Tudor trilogy and his Brandon trilogy, (about Charles Brandon and his wives). Tony also has a popular podcast series, Stories of the Tudors. For more information about Tony’s books visit his website www.tonyriches.com and his blog, The Writing Desk and find him on  Facebook and Twitter @tonyriches`,
    ],
  },
  {
    firstName: "C. Deanne",
    lastName: "Rowe",
    website: "http://www.cdeannerowe.com/",
    socialMedia: {
      twitter: "http://twitter.com/cdeannerowe",
      instagram: "http://www.instagram.com/cdeannerowe",
      tiktok: "http://www.tiktok.com/@cdeannerowe",
      facebook: "http://www.facebook.com/cdeannerowe",
    },
    umbrellaGenre: ["western"],
    subGenre: ["Small Town Contemporary", "Western Romance"],
    bio: [
      `C. Deanne Rowe was born and raised in southwest Oklahoma. She has also lived in Nebraska, Texas, and California. Iowa has been her home for over thirty years where she lives with her husband, two children and their spouses, five grandchildren, the memory of her hero teacup toy poodle, Allie, and her new rescue French Bulldog, Kendell`,
      `She has always loved writing poetry and short stories and became a published romance author later in life. She has published thirteen books of her own, three in her Valley Series, six in her Cowboy Temptation Series, three in her Puckerbrush series and one non-fiction, Comforted From Heaven. As one of the Stiletto Girls, she is an author of eleven novellas in the Stiletto Girls Series.`,
      `Learn more about C. Deanne Rowe, her books, sign up for her newsletter, and receive a free ebook at: www.cdeannerowe.com`,
    ],
  },
  {
    firstName: "Misty",
    lastName: "Rogers",
    website: "https://mistyrogersauthor.wordpress.com/",
    socialMedia: {
      instagram: "https://instagram.com/mistyrogers_author",
    },
    umbrellaGenre: ["romance"],
    subGenre: ["Contemporary Romance"],
    bio: [
      `Misty has kept a journal since the age of seven, always enamored with the act of documenting life with words on paper. She dreamed of compiling her journal entries into a biography style book, later realizing that her life probably wasn’t book-worthy. Throughout the years Misty has ventured into blogging, running a fun site and YouTube channel during her college years. Professionally, Misty works in Marketing and has been copy writing for several years.`,
    ],
  },
  {
    firstName: "Daniel J.",
    lastName: "Barnes",
    website: "https://daniel-j-barnes-shop.sellfy.store/",
    socialMedia: {
      instagram: "https://www.instagram.com/djbwriter/",
      facebook: "https://www.facebook.com/DJBWriter/",
      twitter: "https://twitter.com/writerdjb",
    },
    umbrellaGenre: ["fantasy", "horror", "drama", "thriller", "childrens"],
    subGenre: ["Macabre"],
    bio: [
      `Daniel J. Barnes is a multi genre author from the United Kingdom known for several novels, such as...`,
      `Vatican: The Angel of Justice series`,
      `The Secret Hunter’s Horde series`,
      `Fear Trigger.`,
      `Blood Stained Canvas`,
      `Dinner Party`,
      `Welcome to Crimson`,
      `Maple Malls Massacre`,
      `Hartwaker series`,
      `Monster Meals`,
    ],
  },
  {
    firstName: "Brent",
    lastName: "Archer",
    website: "https://brentarcher.net/",
    socialMedia: {
      instagram: "https://www.instagram.com/brent_archer_writer/",
      facebook: "https://www.facebook.com/brent.archerauthor/",
      twitter: "https://twitter.com/brentarcherwrit",
    },
    umbrellaGenre: ["romance"],
    subGenre: ["Gay Contemporary", "Gay Suspense"],
    bio: [
      `Brent Archer was born in Spokane, Washington, and lived there most of his adolescent life. At 18, he left for Seattle to attend the University of Washington for Electrical Engineering. Quickly, it became apparent that he hated his science classes, and so he switched his major to International Studies with a minor in history. After graduation, he got several accounting jobs while pursuing an acting career in musical theater and dance. Once thirty hit, however, he decided to focus on numbers, getting a certificate in accounting, and became the Financial Controller of a non-profit arts and music organization.`,
      `Though writing most of his life, he never thought to submit his work for publication. In 2012, he visited his cousin Delilah Devlin in Arkansas and she prodded him to write a story and submit it. So, he did and the story, Dear Bryan, sold right away. With the encouragement of Delilah, his other writing cousin Elle James, and his husband, Brent embarked on a writing career. He’s loving the journey, finding inspiration and a story everywhere he goes, whether it be the local coffee shop, driving through the U.S., or riding the train exploring the world. So far, he’s visited England, Scotland, Iceland, France, Switzerland, Austria, the Czech Republic, Germany, the Netherlands, Belgium, Norway, China, New Zealand, and driven through most of the United States and a good chunk of Canada. His goal is to visit each continent and every US state. When not writing or traveling, Brent works in a local wine shop…. It’s research for that next writing project!`,
      `He is published with House of Erotica and Cleis Press, and he is currently self-publishing through Amazon and Kobo.`,
    ],
  },
  {
    firstName: "N.S.",
    lastName: "Neill",
    website: "",
    socialMedia: {
      instagram: "https://www.instagram.com/the_shadow_jackal",
      facebook: "https://www.facebook.com/NSNeillAuthor",
    },
    umbrellaGenre: ["thriller", "horror"],
    subGenre: ["Crime"],
    bio: [
      `N S Neill lives at home with her husband, dog and cat. She is a writer and avid reader of crime, horror and thrillers with a love for fairytales and dinosaurs as well. Her favourite books include Jurassic Park, Alice’s Adventures in Wonderland, Sleepy Hollow, and The Hound of the Baskervilles.`,
      `Her works are available via ebook and paperback on Amazon worldwide.`,
    ],
  },
  {
    firstName: "Laura",
    lastName: "Akers",
    website: "https://lauraakers.com/",
    socialMedia: {
      instagram: "https://www.instagram.com/thelauraakers/",
      facebook: "https://www.facebook.com/LauraAkersAuthor/",
      twitter: "https://twitter.com/LauraAkers",
      tiktok: "https://www.tiktok.com/@thelauraakers?",
    },
    umbrellaGenre: ["thriller"],
    subGenre: ["Mystery Action"],
    bio: [
      `HOW A DEATH THREAT LEAD ME FROM BEING A PROSECUTOR TO AN AUTHOR`,
      `“I think everyone should focus on situational awareness. Stay alert, and stay alive!” – Laura Akers`,
      `I was raised in the Imperial Valley, California, by parents who worked in education. As an adopted only child, I spent most of my time reading books, being a “band geek” playing trumpet and piano, and riding horses.`,
      `After law school, I became a prosecuting attorney and handled the worst violent crimes. A person I convicted threatened me, and I trained with a former CIA operative in self-defense. This led to my creation of Dior or Die’s protagonist, Davia Glenn. She’s someone who refuses to quit, no matter the odds, and it’s a philosophy I live by.`,
      `While this all sounds rather achievement-driven, I also like to take beach photos and listen to audiobooks.  In the evenings, I chill while watching Korean dramas.`,
    ],
  },
  {
    firstName: "Alexandra",
    lastName: "Peel",
    website: "https://www.sticksandstonesbooks.com/",
    socialMedia: {
      instagram: "https://www.instagram.com/alexandra.peel/",
      twitter: "https://twitter.com/alexandrapeel",
    },
    umbrellaGenre: ["fantasy"],
    subGenre: ["Steampunk"],
    bio: [
      `Visual artist turned author, with a Degree in Fine Art, Sculpture. Has been a freelance community artist, painter, graphics tutor, and bookseller; currently works as a Learning Support Practitioner in F.E.`,
    ],
  },
  {
    firstName: "Mark O",
    lastName: "Piggott",
    website: "https://authormarkpiggott.com/",
    socialMedia: {
      instagram: "http://www.instagram.com/author.markpiggott",
      twitter: "http://www.twitter.com/Author_MPiggott",
      facebook: "http://www.facebook.com/authormpiggott",
      tiktok: "http://www.tiktok.com/authormpiggott",
    },
    umbrellaGenre: ["fantasy", "scifi"],
    subGenre: ["Steampunk"],
    bio: [
      `Mark Piggott, a native of Phillipsburg, N.J., enlisted in the U.S. Navy in 1982, beginning a 23-year career.`,
      `He served on four aircraft carriers and various duty stations as a Navy Journalist before he attained the rank of Chief Petty Officer. He retired from active duty in 2006.`,
      `His first novel, Forever Avalon, was published in 2009, followed by his second novel, The Dark Tides, in 2014. The Outlander War: Book Three of the Forever Avalon series from Austin Macauley Publishing was released in 2020. In 2021, he published the start of a new steampunk fantasy series with The Last Magus: A Clockwork Heart from Lulu.com. At the end of 2021, Mark signed with Curious Corvid Publishing as one of their new authors for this small, independent publisher.`,
      `His novels have won a slew of awards over the past years. The Outlander War won second place for fantasy in the 2021 Firebird Book Awards, The Last Magus won first place for steampunk, and in 2022, Forever Avalon won second place for fantasy. Additionally, The Last Magus: A Clockwork Heart won the Grand Prize for Fiction in the 2022 Authors Marketing Guild Indie Book Awards and 3rd Place in Fantasy-Myths and Legends in The BookFest 2022 Book Awards.`,
      `His latest fantasy novella, The River of Souls, in collaboration with poet Ashley Valitutto, was published in 2022 through Curious Corvid Publishing, winning two Firebird Book Awards and nominated for two Indie Book Awards. Additionally, Forever Avalon was made into an audiobook, narrated by voice artist Traci Odom, followed by The Last Magus: A Clockwork Heart, narrated by Melissa Barnes.`,
      `In 2023, the steampunk historical fiction Corsair and the Sky Pirates launched, winning two 2nd Place awards from The BookFest in Fantasy-Gaslamp and Sci-Fi-Steampunk. Coming soon, the next book in The Last Magus series, Dragonfire and Steel, and the fourth book in the Forever Avalon series, The Prometheus Engine!`,
    ],
  },
  {
    firstName: "Rachael",
    lastName: "Huszar",
    website: "https://www.rachaelhuszar.com/",
    socialMedia: {
      instagram: "https://www.instagram.com/rachaelhuszarisawriter",
    },
    umbrellaGenre: ["fantasy", "romance", "western"],
    subGenre: ["Historical Fantasy", "Action/Adventure"],
    bio: [
      `Rachael Huszar kept her life steeped in stories from a young age, and she began her own journey in story-making when she reached adulthood. In the time since, she has taken up swimming, roller skating, and consuming tabletop RPG streams. She spends the bulk of her time with her dog, Silo, and works full time as a designer in Dallas, Texas.`,
    ],
  },
  {
    firstName: "Marian L",
    lastName: "Thorpe",
    website: "https://marianlthorpe.com/",
    socialMedia: {
      twitter: "https://twitter.com/marianlthorpe",
    },
    umbrellaGenre: ["fantasy", "drama"],
    subGenre: ["Historical Fantasy", "Alternate History", "LGBTQ+"],
    bio: [
      `After two careers as a research scientist and an educator, I decided it was time to do what I'd always really wanted, and be a writer. As well as my novels, I've published short stories and poetry. My life-long interest in Roman and post-Roman European history provided the inspiration for my books, while my other interests in landscape archaeology and birding provide background.`,
    ],
  },
  {
    firstName: "Maia",
    lastName: "Strong",
    website: "https://www.maiastrong.com/",
    socialMedia: {
      twitter: "https://twitter.com/MaiaStrong01",
      instagram: "https://www.instagram.com/maiastrong01/",
      facebook: "https://www.facebook.com/MaiaStrong",
    },
    umbrellaGenre: ["romance", "fantasy"],
    subGenre: ["Queer Romance", "Speculative Romance", "Cozy Paranormal"],
    bio: [
      `Maia Strong (she/her) is a bi writer of sexy, speculative, queer romances as well as the cozy paranormal series, Presence Unknown, Paranormal Investigators. She prefers rain to sunshine, lemon to chocolate, and  will rarely be found without a cup of coffee nearby.`,
    ],
  },
  {
    firstName: "Jean",
    lastName: "Estelle",
    website: "https://www.jeanestelle.com/",
    socialMedia: {
      tiktok: "https://www.tiktok.com/@jean_estelle",
      instagram: "https://www.instagram.com/jeanestelle_hope/",
      facebook: "https://www.facebook.com/junipermikah",
    },
    umbrellaGenre: ["romance", "thriller", "scifi", "dystopian"],
    subGenre: ["Post-Apocalyptic"],
    bio: [
      `In Hope, we meet seventeen year old Juniper Mikah, and the world she lives in. Humans now live underground, 300 years after a nuclear world war. Juniper is set to spend six months in Discovery, where each fresh batch of arrivals learn skills to benefit their home compound. But she has a secret mission: to find out what happened two years ago when her father vanished. Little does Juniper know, what she's about to uncover will shock her to the core...`,
      `Jean has been writing her whole life. Ever since she could hold a pencil, she's been writing. Whether it was small chapter books or short stories, writing has always been her escape. It was a world that she could create, control, and live in. One of her favorite books as a tween was 20,000 Leagues Under the Sea. She could see the story, diving down with Captain Nemo, getting lost in his adventures. The book worn down to nothing from reading it over and over again. There was rarely a time as a child that she didn't have a book in her hands. Her BIGGEST dream is to be able to write for a living, and give her fans the same safe world to get lost in as she created for herself in her work. `,
      `Right now Jean resides in the Poconos with her loving husband and daughters where she has lived there nearly her whole life. She is hard at work on the second book in the Saga, so keep watch! Thank you!`,
    ],
  },
  {
    firstName: "H M",
    lastName: "DuVal",
    website: "https://duvalmichelle.wixsite.com/hmduval",
    socialMedia: {
      instagram: "https://www.instagram.com/author.h.m.duval/",
      facebook: "https://www.facebook.com/HMichelleDuVal",
    },
    umbrellaGenre: ["romance", "fantasy", "scifi", "dystopian"],
    subGenre: [
      "Enemies to Lovers",
      "Science Fiction Romance",
      "Fantasy Romance",
    ],
    bio: [
      `H M DuVal is a mother, Kinesiologist, and author of the Dream Walker series. She has always had a passion for good stories: telling them, sharing them, and getting lost in them. Fiction and fantasy genres, with a healthy dose of romance, are her favorite. She loves the incredible power they have to spirit us away from the mundane and into the sensational, and believes that shift in perspective helps us find the magic inside our own lives. She hopes that while reading her work, you are similarly transported.`,
      `H M DuVal lives in the beautiful Shenandoah Valley with her husband, two children, dog, cat, and horse.`,
      `Follow her on Facebook and Instagram for release news and updates.`,
    ],
  },
  {
    firstName: "Lynne Hancock",
    lastName: "Pearson",
    website: "https://lynnehancockpearson.com/",
    socialMedia: {
      instagram: "https://www.instagram.com/lynnehancockpearson/",
      facebook: "https://www.facebook.com/lynne.hancockpearson/",
    },
    umbrellaGenre: ["romance"],
    subGenre: [
      "Sweet Romance",
      "Contemporary",
      "Grumpy Boss",
      "Seattle Stories",
    ],
    bio: [
      `Lynne Hancock Pearson writes fun, flirty, feel-good fiction that simmers at a low heat. Her stories reflect the power of community.`,
      `She lives near Seattle with two finicky felines and one long-suffering husband. She is a left-handed middle child who grew up in the Great White North and is a proud member of the Métis Nation of Canada.`,
    ],
  },
  {
    firstName: "Zeena",
    lastName: "Becks",
    website: "https://zeenabecks.com/",
    socialMedia: {
      twitter: "https://twitter.com/BecksZeena",
      instagram: "https://www.instagram.com/zeenabecksauthor/",
      facebook: "https://www.tiktok.com/@zeenabecks",
    },
    umbrellaGenre: ["romance", "drama"],
    subGenre: ["Contemporary", "New Adult", "Women's Fiction"],
    bio: [
      `Hey, I'm Zeena Becks, an Indie writer from Germany. I write love and life stories about musicians, dancers, travellers, and equestrians, since those are my favourite hobbies as well. My stories are either set in Germany or England, but they are all written in English (British English).`,
      `Other interests of mine are yoga, psychology (especially inner child work), and love. Love is a must in every book I read. It definitely can be found in every one of mine as well.=)`,
    ],
  },
  {
    firstName: "JC",
    lastName: "Paulson",
    website: "https://www.jcpaulsonwriter.com/",
    socialMedia: {
      twitter: "https://twitter.com/joanne_paulson",
      facebook: "https://www.facebook.com/jcpaulsonauthor/",
      instagram: "https://www.instagram.com/paulson.joanne/",
    },
    umbrellaGenre: ["thriller", "childrens"],
    subGenre: ["Mystery Romance"],
    bio: [
      `Joanne (J.C.) Paulson, a long-time Saskatoon journalist, has been published in newspapers including The StarPhoenix, The Western Producer, the Saskatoon Express, allSaskatchewan and a variety of magazines.`,
      `She is the author of an independently-published mystery series including the novels Adam’s Witness, Broken Through, Fire Lake, Griffin’s Cure, and Two Hundred Bones, a novella. She has also written a historical fiction/western novel entitled Blood and Dust, and a wee children’s book, Magic Mack and The Mischief-Makers.`,
    ],
  },
  {
    firstName: "Tina McLachlan",
    lastName: "Brassington",
    website: "https://travelsintheeastandoest.com/",
    socialMedia: {
      instagram: "https://instagram.com/tinamcbauthor",
      facebook: "https://www.facebook.com/profile.php?id=100087952794320",
    },
    umbrellaGenre: ["thriller"],
    subGenre: ["Cosy Mystery"],
    bio: [
      `After years of studying and working in boring stuff like City banking, business and law, Tina (a Scot) retrained as a further education teacher, which she enjoyed enormously.`,
      `She then moved abroad and rebuilt and developed a derelict farm into a successful eco small holding business with her husband.`,
      `Latterly, after bidding a fond farewell to the farm and menagerie, Tina is now sailing around the Med with her husband and cat - there was no room for the pigs, goats, turkeys, hens, ducks and geese, sadly...`,
      `Between writing and travelling, she enjoys taking on silly roles in TV advertising and doing voice overs.`,
    ],
  },
  {
    firstName: "R. M.",
    lastName: "Krogman",
    website: "https://rmkrogman.com/",
    socialMedia: {
      instagram: "https://www.instagram.com/r.m.krogman",
      facebook: "https://www.facebook.com/rmkrogman",
    },
    umbrellaGenre: ["fantasy"],
    subGenre: ["Epic/High/Dark"],
    bio: [
      `Rebecca M. Krogman is an epic and dark adult fantasy from the central U.S. Her debut novel LIBERATION is the first volume of a larger story set in Midgate, a medieval-inspired world of magic, mermaids, and wyverns.`,
    ],
  },
  {
    firstName: "Melony",
    lastName: "Ann",
    website: "https://www.melonyannauthor.com/",
    socialMedia: {
      instagram: "https://www.instagram.com/melonyannauthor",
      facebook: "https://www.facebook.com/authorsjasonmel",
    },
    umbrellaGenre: ["romance"],
    subGenre: [
      "Sports Romance",
      "Mafia Romance",
      "Paranormal Romance",
      "Taboo Romance",
      "MM Romance",
      "Forbidden Romance",
    ],
    bio: [
      `Melony Ann began writing short stories and poetry as a child. She continued honing her craft over the years until she took the plunge and began publishing her work, despite having severe anxiety.`,
      `Melony writes contemporary romance stories that are full of suspense and a lot of steam.`,
      `When she isn’t writing, she is loving her family and working to make her life something she deserves.`,
      `Melony believes that if her writing can inspire just one person, then all of her hard work is worth it.`,
      `Her hope is that her writing allows each and every one of her readers to escape for a little while. To dive into a different world one book at a time.`,
    ],
  },
  {
    firstName: "Tanya",
    lastName: "Ross",
    website: "https://www.tanyarossauthor.com/",
    socialMedia: {
      instagram: "https://www.instagram.com/tjross_author/",
      facebook: "http://www.facebook.com/fictionauthor54",
    },
    umbrellaGenre: ["dystopian"],
    subGenre: ["Sci-Fi", "Romance"],
    bio: [
      `Tanya Ross was born and raised in San Diego County, her “happy place.” Although Southern California is a particular kind of paradise, she desires a world where everyone is kind, compassionate, and upbeat, which became one of the themes of her first novel, Rising Up. For thirty-two years she was an educator of English, history, AVID, and student leadership. She loved teaching and kids; her students were a daily inspiration. Her exit from the educational arena allowed her to indulge her hopes, dreams, and goals in what she taught for so many years--writing. Her first novel, Rising Up, began her lifelong dream of writing meaningful novels for young adults. When she’s not creating new worlds, you can find her reading, and spending time with her husband and two kids. Discover more on her website:   http://www.tanyarossauthor.com/`,
    ],
  },
  {
    firstName: "G.M.",
    lastName: "Chmilar",
    website: "https://www.gmchmilar.com/books",
    socialMedia: {
      instagram: "https://www.instagram.com/ms.c.ingscribbles/",
    },
    umbrellaGenre: ["romance", "fantasy"],
    subGenre: ["Urban/Contemporary", "Action", "Adventure"],
    bio: [
      `G.M. Chmilar is a first-generation Filipino-Canadian that grew up in cold Alberta. Her favourite things to share are food and stories, because she believes it's how relationships are made. As a child, Gabrielle always loved to write. She carried notebooks to draw or scribble about how fantastical her life could be if only she could use magic.`,
      `The first book, Solum, is the first of the series of The Faith of The Three and it is just that. A place where magic lives and exists hiding in plain sight. Inspiration for her writing comes from various television shows, movies, video games, Dungeons and Dragons, and music. All of this is amalgamated into characters and places that are relatable and close to home. She wanted everyone to find something to love in her books.`,
      `She still lives and works in Alberta. In her spare time, Gabrielle’s wide variety of hobbies keeps her busy such as: video games, baking, longboarding, yoga, and hanging with The Boys.`,
      `Gabrielle believes that you should always strive to be the person you needed to be when you were younger.`,
    ],
  },
  {
    firstName: "Sera",
    lastName: "Cassell",
    website: "https://www.seracassell.com/",
    socialMedia: {
      instagram: "http://www.instagram.com/seracassell/",
      facebook: "http://www.facebook.com/authorseracass",
      twitter: "https://twitter.com/seracassell",
    },
    umbrellaGenre: ["romance"],
    subGenre: ["Contemporary"],
    bio: [
      `Sera Cassell is addicted to writing fun, steamy romance with feisty heroines and the swoon-worthy heroes who fall for them. Her books always have a happily ever after and more than likely, a nod to her Irish and Scottish heritage. She is living her own happily ever after in New England with her adrenaline junkie husband and their family. In addition to writing, her passions are reading, eating New Haven style pizza, sipping London Fog tea lattes, and chocolate. Any kind. She has never met a piece of chocolate she doesn't like.`,
    ],
  },
  {
    firstName: "Mia",
    lastName: "Sivan",
    website: "https://www.miasivan.com/",
    socialMedia: {
      instagram: "https://www.instagram.com/miasivan.author/",
      facebook: "https://www.facebook.com/MiaSivanAuthor",
      twitter: "https://twitter.com/FreidlinSivan",
    },
    umbrellaGenre: ["romance"],
    subGenre: ["Contemporary"],
    bio: [
      `My name is Mia Sivan`,
      `I am  an Israeli woman who lives, works and loves in Tel Aviv. The city is as much a part of my books as any other character.`,
      `I worked as a senior investment manager for many years, and the books I write draw much from my personal experience, as well as real-life scams that took place in the Israeli financial market.`,
      `When not writing or dreaming up steamy scenes, I enjoy long walks by the beach (it’s Tel Aviv, it’s never too cold).`,
    ],
  },
  {
    firstName: "Samantha",
    lastName: "Michaels",
    website: "https://www.samanthamichaelsbooks.com/",
    socialMedia: {
      instagram: "https://www.instagram.com/samanthamichaelsauthor/",
      facebook: "https://www.facebook.com/SamanthaMichaelsBooks",
      tiktok: "https://www.tiktok.com/@samantha.michaels.author?lang=en",
    },
    umbrellaGenre: ["romance"],
    subGenre: ["Contemporary"],
    bio: [
      `Samantha Michaels was born in 1973 in the small town of Abington, PA and was raised and still lives in Hatboro, PA (both suburbs of Philadelphia).  She is married to her high school sweetheart and they have a rescue dog, a beautiful Black Lab named Holly.`,
      `When she’s not writing or working at her full-time job, she enjoys watching her Philly sports team (hopefully) win, listening to heavy metal/hard rock music, Texas Hold Em, reading, and spending time with friends and family.`,
      `Her love of reading began at a young age, thanks to her mother and Sesame Street.  Her mom read to her constantly, and by three years old, she was reading on her own, and hasn’t stopped.  This eventually turned into a love of writing.  She was writing for herself and then for a small group of friends, one of whom told her she should be writing books.  She took her friends advice and has since published several romance books with plenty more on the way.`,
    ],
  },
  {
    firstName: "Marie",
    lastName: "Jones",
    website: "http://www.mariejonesbritishwriter.com/",
    socialMedia: {
      instagram: "http://www.instagram.com/mariejoneswriter",
      facebook: "http://www.facebook.com/mariejoneswriter",
      twitter: "http://www.twitter.com/mariejones14057",
      tiktok: "http://www.tiktok.com/marie_jones_author",
    },
    umbrellaGenre: ["romance", "thriller"],
    subGenre: ["Women's", "Suspense", "Crime"],
    bio: [
      `Readers Favorite Gold Award Winner 2022`,
      `NYC Big Book Award Winner 2022 - Romantic Thriller`,
      `Finalist American Fiction Awards 2022`,
      `Chatelaine Romance Fiction First Place Winner 2023`,
      `Amor Book Award Finalist 2022`,
      `Author of multi award winning romantic suspense/thriller Those We Trust series`,
      `published with GenZ Publishing`,
      `Semi finalist Australasian Screenwriting Competition`,
      `Double recommendation from Stage 32`,
      `Marie Jones’ passion for writing and creating stories began from a young age, where she loved nothing more than writing stories into her special A4 lined book. Later on in life, Marie went on to study creative writing at night college. Her favourite place to write is in her lounge when the house is quiet (though have learnt to write around noise!).`,
    ],
  },
  {
    firstName: "Billie Jade",
    lastName: "Kermack",
    website: "http://www.billiejadekermack.co.uk/",
    socialMedia: {
      instagram: "https://www.instagram.com/billiejadekermackauthor",
    },
    umbrellaGenre: ["romance", "horror", "comedy"],
    subGenre: ["Friends-Lovers", "Murder Mystery", "Paranormal"],
    bio: [
      `Billie Jade Kermack was born and raised in London, England. She lives with her partner, three kids and her dippy dog Gus. As well as being an author Billie Jade works as a Makeup and SFX artist and a doll maker.`,
      `Her love of horror, murder mystery and magic inspired her to create her first paranormal romance trilogy AWOKEN, ASCEND & HALLOWED.`,
      `Her latest release is the well-received VERONICA, a mature friends to lovers with a non-traditional happily ever after filled with humour. This is the first standalone book in the planned TWISTED FATE series. Creating swoon-worthy book boyfriends is an obsession at this point.`,
    ],
  },
  {
    firstName: "Tori",
    lastName: "Alvarez",
    website: "https://www.torialvarez.com/",
    socialMedia: {
      instagram: "https://www.instagram.com/mstorialvarez/?hl=en",
      tiktok: "https://www.tiktok.com/@mstorialvarez?lang=en",
      facebook: "https://www.facebook.com/tori.alvarez.3551",
    },
    umbrellaGenre: ["romance"],
    subGenre: ["New Adult"],
    bio: [
      `Tori Alvarez is an educator by day and author by night. She spent her days daydreaming different stories and scenes so she finally took the plunge and began putting them down on paper.`,
      `She writes real, honest romance with a hint of steam. She is a sucker for happily ever afters, so you will always find them in her books too.`,
      `Tori is a Texas girl, born and raised. She lives in South Central Texas with her husband, teen daughter, dog & cat.`,
    ],
  },
];
